apiVersion: v1
kind: Service
metadata:
  name: fts-postgres
  labels:
    app.kubernetes.io/name: fts-postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    name: client
  selector:
    app.kubernetes.io/name: fts-postgres
