apiVersion: apps/v1
kind: Deployment
metadata:
  name: fts-webapp
  labels:
    app.kubernetes.io/name: fts-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fts-webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fts-webapp
    spec:
      containers:
      - name: app
        image: ghcr.io/nlnwa/fts-webapp
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: webapp-env
          - secretRef:
              name: postgres-env
        ports:
        - containerPort: 8501
          name: http
          protocol: TCP
