apiVersion: v1
kind: Service
metadata:
  name: fts-webapp
  labels:
    app.kubernetes.io/name: fts-webapp
spec:
  type: NodePort
  ports:
  - port: 8501
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: fts-webapp
