apiVersion: batch/v1
kind: Job
metadata:
  name: fts-indexer
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fts-indexer
    spec:
      restartPolicy: Never
      containers:
      - name: indexer
        image: ghcr.io/nlnwa/fulltekstsok-indexer:main
        imagePullPolicy: IfNotPresent
        args: ["default", "/mnt/data"]
        envFrom:
          - secretRef:
              name: postgres-env
        volumeMounts:
          - name: warcs
            mountPath: /mnt/data/default
      volumes:
        - name: warcs
          persistentVolumeClaim:
            claimName: warcs
            readOnly: true
