apiVersion: batch/v1
kind: Job
metadata:
  name: process-nlwa-html-01
spec:
  template:
    metadata:
      labels:
        app: process-nlwa-html
    spec:
      restartPolicy: Never
      containers:
      - name: main-01
        image: harbor.nb.no/sprakbanken/nlwa_index_html:2023_02_02_1
        command: ["python3", "process-warc-html.py", "jobs/x-01.csv"]
        env:
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_DB
            value: "nlwa_index"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sprakbank-postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            value: "sprakbank-postgres"
          - name: POSTGRES_PORT
            value: "5432"
        volumeMounts:
          - name: sprakbank-fs00
            mountPath: /mnt/data
      volumes:
        - name: sprakbank-fs00
          persistentVolumeClaim:
            claimName: sprakbank-fs00-ro-pvc
