apiVersion: v1
kind: Pod
metadata:
  name: nlwa-index-helper
spec:
  containers:
    - name: nlwa-index-helper
      image: registry.nb.no:5000/sprakbanken/nlwa_index_helper:2022-09-20-1
      env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "nlwa_index_heritrix"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sprakbank-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "sprakbank-postgres"
        - name: POSTGRES_PORT
          value: "5432"
      command: [ "/bin/sh" ]
      args: [ "-c", "sleep infinity"]
      volumeMounts:
        - name: sprakbank-fs01
          mountPath: /mnt/data
  volumes:
    - name: sprakbank-fs01
      persistentVolumeClaim:
        claimName: sprakbank-fs01-ro-pvc
