apiVersion: v1
kind: Pod
metadata:
  name: nlwa-index-helper
spec:
  containers:
    - name: nlwa-index-helper
      image: harbor.nb.no/sprakbanken/nlwa-index-helper:2023_02_02_1
      env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "nlwa_index"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sprakbank-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "sprakbank-postgres"
        - name: POSTGRES_PORT
          value: "5432"
      command: [ "/bin/sh" ]
      args: [ "-c", "sleep infinity"]
      volumeMounts:
        - name: sprakbank-fs00
          mountPath: /mnt/data
  volumes:
    - name: sprakbank-fs00
      persistentVolumeClaim:
        claimName: sprakbank-fs00-ro-pvc
