apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres
  - webapp
  - indexer

secretGenerator:
  - name: postgres-env
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=fts-postgres
      - POSTGRES_PORT=5432
