apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlwa-webapp-deployment
  labels:
    app: nlwa-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nlwa-webapp
  template:
    metadata:
      labels:
        app: nlwa-webapp
    spec:
      containers:
      - name: nlwa-webapp
        image: registry.nb.no:5000/sprakbanken/nlwa-webapp:2022-08-09-1
        envFrom:
          - configMapRef:
                name: sprakbank-postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sprakbank-postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            value: "sprakbank-postgres"
          - name: POSTGRES_PORT
            value: "5432"
        ports:
        - containerPort: 8501
